language: node_js
cache:
directories:
  - node_modules
notifications:
email: false
node_js:
  - '7'
branches:
except:
  - /^v\d+\.\d+\.\d+$/
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu
